### ISSUE TITLE
Healthcheck script last 5min time calculation does not take TZ into account

### ISSUE THREAD

**Issue by kbuc** [sdr-enthusiasts/docker-flightradar24#170]
At least on my system, the logs in fr24 container are in UTC time and the healthcheck script always gives:

`($TIMESTAMP_NOW - $LOG_LAST_ENTRY_TIMESTAMP)` around 7200 (my TZ is UTC+2), so it's always
`No data sent data to fr24feed in past 5 mins. UNHEALTHY`, even though the feeder is working fine. 

I'm not sure how other systems are configured, but probably some  `-u` should be used when interpreting the date taken from log? Now it is assuming the parsed date is in the local TZ, but it's not, at least in my case.

**Comment by markrmccracken** [comment]
I haven't checked the logs inside the container, but I"m having the same issue with that check always being found unhealthy and causing the container to restart at every check. 

![image](https://github.com/sdr-enthusiasts/docker-flightradar24/assets/39926378/b406b4bb-11bf-4e8c-88d4-7cf6b32a0687)

**Comment by kx1t** [comment]
The container timezone is always in UTC, and when measuring time, we use relative time (seconds since epoch). Having said this, the HealthCheck routine underwent a bunch of changes in the last few days, and this should have solved the issue.

If you still see this, please let me know and/or feel free to reopen this issue. Thanks!

**Comment by gnilebein** [comment]
I have the same problem and my container is always displayed as unhealty. The two timestamps differ pretty much exactly by the two hours of the time zone offset.

```
root@fr24feed:/# LOG_LAST_ENTRY=$(grep -a '\[feed\]\[i\]sent' /var/log/fr24feed.log | tail -1)
root@fr24feed:/# LOG_LAST_ENTRY_TIMESTAMP=$(date --date="$(echo "$LOG_LAST_ENTRY" | cut -d ' ' -f 1,2)" +%s.%N)
root@fr24feed:/# LOG_LAST_ENTRY_TIMESTAMP=$(date --date="$(echo "$LOG_LAST_ENTRY" | cut -d ' ' -f 1,2)" +%s.%N)
root@fr24feed:/# echo $LOG_LAST_ENTRY
2024-08-04 20:03:16 | [feed][i]sent 0,6 AC
root@fr24feed:/# echo $LOG_LAST_ENTRY_TIMESTAMP
1722794596.000000000
root@fr24feed:/# echo $TIMESTAMP_NOW
1722801731.690693460
```
