### ISSUE TITLE
FR24

### ISSUE THREAD

**Issue by billcastroTT** [sdr-enthusiasts/docker-flightradar24#224]
when I run the script in the instruction I get the following error:

s6-envdir: fatal: unable to envdir /run/s6/container_environment: No such file or directory

**Comment by lg** [comment]
hey i got this working by just following the manual instructions either: https://sdr-enthusiasts.gitbook.io/ads-b/feeder-containers/feeding-flightradar24#manual-sign-up-method or https://github.com/sdr-enthusiasts/docker-flightradar24#script-method. i forget which one i did which made this work, but one of the two should.

**Comment by kbob76** [comment]
Yup manual method worked, had to get around by exec'ing into the container and manually adding the code snippet to the prometheus yaml file.

**Comment by Guzbikes** [comment]
I'm also getting the same error. 

But when I used: 
https://github.com/sdr-enthusiasts/docker-flightradar24?tab=readme-ov-file#script-method
and filled in the fields myself, it worked fine

The only difference in https://sdr-enthusiasts.gitbook.io/ads-b/feeder-containers/feeding-flightradar24#automatic-sign-up-script-method is the line: `--entrypoint /scripts/signup.sh`

Interesting, have to do some more poking around. Anyone else figure it out?

**Comment by kx1t** [comment]
The signup process was indeed broken after changes made by FR24. As a result, we completely overhauled the signup process in the last few days. Using the new instructions in the README.md, you should be able to sign up for an ADSB feeder key and for a UAT feeder key.

**Comment by lg** [comment]
clever to use qemu to run the damn thing 👏
