### ISSUE TITLE
Own NTP server

### ISSUE THREAD

**Issue by BeginnerOfLife** [sdr-enthusiasts/docker-flightradar24#40]
Hello 😀
Is it possible to get an own environment variable for local ntp server? So if the ISP is down the drift won't be too high.
Thanks and bist regards,
Christian

**Comment by mikenye** [comment]
Hello Christian,

I'd like to implement this, however I'm not sure how.

Looking at the FR24 forums, [there's been some discussion of this](https://forum.flightradar24.com/forum/radar-forums/flightradar24-feeding-data-to-flightradar24/10363-fr24feed-on-raspberry-pi-frequent-dns-requests-for-ntp).

The workaround appears to be to [manually "spoof" the DNS server addresses](https://forum.flightradar24.com/forum/radar-forums/flightradar24-feeding-data-to-flightradar24/10363-fr24feed-on-raspberry-pi-frequent-dns-requests-for-ntp?p=105895#post105895).

However, that's not a good solution, and not something I want to implement.

If you know something that can be added to the fr24feed.ini file to make it use a user-defined NTP server, I will happily implement it.

Thanks.
