### ISSUE TITLE
Timestamp errors are back

### ISSUE THREAD

**Issue by HrJosch** [sdr-enthusiasts/docker-flightradar24#53]
Since this morning MLAT Timestamp errors are back. The fr24 container remains in status 'starting'. Could you please look into it?

**Comment by mikenye** [comment]
@HrJosch can you please post your container log from start up? Please make sure you remove any personally identifiable information before submitting. Thanks.

**Comment by mikenye** [comment]
I will note that with the geopolitical climate right now, it looks like FR24 are being pummelled.... :(

**Comment by HrJosch** [comment]
[_fr24_logs.txt](https://github.com/sdr-enthusiasts/docker-flightradar24/files/8130247/_fr24_logs.txt)
Sure, logs attached. Thank you!

**Comment by mikenye** [comment]
Can you please run `ntpq -pn` on your host, and paste the output?

**Comment by HrJosch** [comment]
-bash: ntpq: command not found

**Comment by mikenye** [comment]
How are you synchronising the time on your host? I just want to make sure the time on the host is accurate. Typically this is done with NTP or Chrony. It looks like your host does not have NTP installed.

**Comment by HrJosch** [comment]
My adsb stack runs on OMV6. Timesync is done via NTP pool.ntp.org

**Comment by HrJosch** [comment]
Basically this issue is the same as I described in issue #38 
`[readsb] 2022/02/24 07:15:29 Basestation TCP output: Send Error: Broken pipe: xxx.xx.x.x port 41610 (fd 19, SendQ 88, RecvQ 0)
`

**Comment by mikenye** [comment]
What's your source of BEAST data?

Incidentally, I see on their forums:

```
FR24 WILL ONLY USE MLAT DATA CAPTURED WITH 'DVBT'+DUMP1090-MUTABILITY WITH --MLAT OPTION DIRECT (TCP not valid)
```

**Comment by mikenye** [comment]
Is your MLAT sync working for other services? It might be worth checking your sync on ADSB Exchange, as they provide pretty good detail about MLAT status.

That will be able to confirm whether the problem is with FR24 or not.

**Comment by HrJosch** [comment]
ADSB Exchange looks good:

Feeder ShortID : XXXXX-XXXXX

[MSG-1] ADSBx is recieving your stats data.
This is a separate service from the feeder software.



Aircraft count logged 1600 times (every 60 seconds), last seen (1645686576.4562 seconds since epoc) Thursday 24th of February 2022 07:09:36 AM UTC

**Comment by HrJosch** [comment]
Flightaware:

Feeder Mode: Mode-S (1090 MHz)
Multilateration (MLAT): Supported / Enabled

**Comment by mikenye** [comment]
See if you can find your ADSBx feeder in here: https://adsbx.org/sync/

**Comment by mikenye** [comment]
if you could post a screenshot showing health, timeout, peers, sync-statuses cells for your feeder, that would be great.

**Comment by HrJosch** [comment]
![Bildschirmfoto 2022-02-24 um 08 43 53](https://user-images.githubusercontent.com/30878919/155480478-c4f70b89-da9b-41bc-9f42-8b34de20af0a.png)
![Bildschirmfoto 2022-02-24 um 08 44 28](https://user-images.githubusercontent.com/30878919/155480495-d4b57d5e-a78d-4340-8dd8-0084f05ee1a1.png)

**Comment by HrJosch** [comment]
![Bildschirmfoto 2022-02-24 um 08 53 27](https://user-images.githubusercontent.com/30878919/155481706-dd92faa7-10a0-4377-a4d4-82f88fcdd288.png)
![Bildschirmfoto 2022-02-24 um 08 53 45](https://user-images.githubusercontent.com/30878919/155481722-dedc292c-9684-4547-bd80-8b788a99904d.png)

**Comment by mikenye** [comment]
It looks like there's nothing wrong with your system. This may be an FR24 server-side issue. Maybe consider disabling MLAT, or see if it eventually comes good.

**Comment by HrJosch** [comment]
Meanwhile the FR24 container became green again and says healthy in Portainer.  I noticed that the adsbexchange health status for my feed is unavailable from time to time.

**Comment by HrJosch** [comment]
> I will note that with the geopolitical climate right now, it looks like FR24 are being pummelled.... :(

You are absolutely right, they can't handle the requests anymore and established a waiting room as a temporary measure while adding resources.  Thank you for your efforts @mikenye! Keep up the good work!
